### ISSUE TITLE
Switch '$id's and '$ref's to HTTPS

### ISSUE THREAD

**Issue by patrickkwang** [NCATSTranslator/OperationsAndWorkflows#52]

**Comment by dkoslicki** [comment]
Basically, in [this line](https://github.com/NCATSTranslator/OperationsAndWorkflows/blob/main/schema/operation.json#L3) of operation.json (and the workflow.json), update to `http` (i.e. use https)

**Comment by finnagin** [comment]
Looks like We might need to update generate_schema.py on lines [81](https://github.com/NCATSTranslator/OperationsAndWorkflows/blob/9addb73b4daddb8345fdf2388a0c9545fda118b0/schema/build/generate_schema.py#L81), [97](       https://github.com/NCATSTranslator/OperationsAndWorkflows/blob/9addb73b4daddb8345fdf2388a0c9545fda118b0/schema/build/generate_schema.py#L97), and [100](https://github.com/NCATSTranslator/OperationsAndWorkflows/blob/9addb73b4daddb8345fdf2388a0c9545fda118b0/schema/build/generate_schema.py#L100).

**Comment by kennethmorton** [comment]
Resolved as or release 1.0.1
