### ISSUE TITLE
Add a composite_operation field

### ISSUE THREAD

**Issue by finnagin** [NCATSTranslator/OperationsAndWorkflows#55]
- [x] Modify [schema.json](https://github.com/NCATSTranslator/OperationsAndWorkflows/blob/main/operations/validation/schema.json) to allow the validator to pass with the additional field
- [x] Identify all of the composite operations
- [x] Add an additional field named `composite_operation` to each of those containing an ordered list of the operations used.

**Comment by finnagin** [comment]
@patrickkwang @cbizon @dkoslicki @edeutsch Does anyone know if there is another composite operation besides lookup and lookup+score? I just looked through the yamls and none of the other operations looked like composite operations to me.

**Comment by dkoslicki** [comment]
Not that I'm aware of

**Comment by dkoslicki** [comment]
PR merged
