### ISSUE TITLE
schema link needs updated to 1.0.1

### ISSUE THREAD

**Issue by dkoslicki** [NCATSTranslator/OperationsAndWorkflows#61]
While the v1.0.0 link for the schema works: https://standards.ncats.io/operation/1.0.0/schema
the v1.0.1 version is 404-ing: https://standards.ncats.io/operation/1.0.1/schema

This will need to be updated.

**Comment by kennethmorton** [comment]
Taken care of with recent changes. New versions require that a branch be created with the corresponding number. See also a newly created index.

https://standards.ncats.io
