### ISSUE TITLE
Exclude Functionality

### ISSUE THREAD

**Issue by capasfield** [NCATSTranslator/OperationsAndWorkflows#77]
Discussion held during 10/4/22 Ops & Workflow meeting ([agenda](https://docs.google.com/document/d/1nXkk3ItKWf4bW0YbGVqUs1rMbDKrfyxkHXTVy9t1J7c/edit?pli=1#))

ARAXi has `exclude=true` for edges that allows us to find entities that are not connected by a certain edge.
TCDC group has been using this functionality
It’s technically TRAPI compliant
Do we want this functionality to be more widely accessible/implemented?

ticket [
ticket https://github.com/NCATSTranslator/testing/issues/227
](https://github.com/NCATSTranslator/testing/issues/227)

**Comment by edeutsch** [comment]
This was proposed by me to the TRAPI group in Dec 2021
https://github.com/NCATSTranslator/ReasonerAPI/pull/306

But after a lot of discussion, there was still opposition to including it in the TRAPI spec.

I was the only one pushing for it. Several were fine with it, but there was also opposition to it.

Therefore it remains an ARAX-only feature.

It is still on the list of things to be considered for TRAPI 1.4, but the current voting at https://github.com/NCATSTranslator/ReasonerAPI/discussions/378 seems to put it pretty far down the list.

So, for now, if you want this kind of functionality, use ARAX. If you want this functionality to be more widely implemented, then the discussion needs some more votes and the pull request needs some vocal support.

**Comment by karafecho** [comment]
I believe this issue is under active discussion in the Ops & Workflows WG. A related issue arose in the QotM. Specifically, a SME asked requested a functionality to compare lists: compare lists of genes, e.g., extract those that are up/down regulated.

**Comment by dkoslicki** [comment]
Closing due to [this comment](https://github.com/NCATSTranslator/Feedback/issues/55#issuecomment-1377885452). Basically, part of this has moved to TRAPI, the other part is more fit for being handled at the UI level
